WebGestion/WebGestion/Models/TiposFacturas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposFacturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposFacturas()
        {
            this.FacturasClientes = new HashSet<FacturasClientes>();
            this.FacturasProveedores = new HashSet<FacturasProveedores>();
        }
    
        public int Id { get; set; }
        public string Prefijo { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasClientes> FacturasClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasProveedores> FacturasProveedores { get; set; }
    }
}

WebGestion/WebGestion/Controllers/TiposFacturasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebGestion.Models;

namespace WebGestion.Controllers
{
    public class TiposFacturasController : BaseController
    {
        private GesemEntities db = new GesemEntities();

        // GET: TiposFacturas/Index
        public ActionResult Index()
        {
            return PartialView(db.TiposFacturas.ToList());
        }

        /*
        // GET: TiposFacturas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TiposFacturas tiposFacturas = db.TiposFacturas.Find(id);
            if (tiposFacturas == null)
            {
                return HttpNotFound();
            }
            return PartialView(tiposFacturas);
        }
        */

        // GET: TiposFacturas/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: TiposFacturas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Prefijo,Descripcion,FacturasClientes,FacturasProveedores")] TiposFacturas tiposFacturas)
        {
            if (ModelState.IsValid)
            {
                db.TiposFacturas.Add(tiposFacturas);
                db.SaveChanges();
                DisplaySuccessMessage("Has append a TiposFacturas record");
                return JsonRedirectToAction("Index");
            }

            DisplayErrorMessage();
            return PartialView(tiposFacturas);
        }

        // GET: TiposFacturas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TiposFacturas tiposFacturas = db.TiposFacturas.Find(id);
            if (tiposFacturas == null)
            {
                return HttpNotFound();
            }
            return PartialView(tiposFacturas);
        }

        // POST: TiposFacturas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Prefijo,Descripcion,FacturasClientes,FacturasProveedores")] TiposFacturas tiposFacturas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tiposFacturas).State = EntityState.Modified;
                db.SaveChanges();
                DisplaySuccessMessage("Has update a TiposFacturas record");
                return JsonRedirectToAction("Index");
            }
            DisplayErrorMessage();
            return PartialView(tiposFacturas);
        }

        // GET: TiposFacturas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TiposFacturas tiposFacturas = db.TiposFacturas.Find(id);
            if (tiposFacturas == null)
            {
                return HttpNotFound();
            }
            return PartialView(tiposFacturas);
        }

        // POST: TiposFacturas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TiposFacturas tiposFacturas = db.TiposFacturas.Find(id);
            db.TiposFacturas.Remove(tiposFacturas);
            db.SaveChanges();
            DisplaySuccessMessage("Has delete a TiposFacturas record");
            return JsonRedirectToAction("Index");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save changes was unsuccessful.";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebGestion/WebGestion/Views/TiposFacturas/Create.cshtml
@model WebGestion.Models.TiposFacturas

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TiposFacturas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("EditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebGestion/WebGestion/Views/TiposFacturas/Edit.cshtml
@model WebGestion.Models.TiposFacturas

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TiposFacturas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("EditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary" value="Save" />
                <input type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal" value="Delete" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Delete", "TiposFacturas", new { id=Model.Id}))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-warning">Delete</button>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebGestion/WebGestion/Views/TiposFacturas/EditForm.cshtml
@model WebGestion.Models.TiposFacturas

        <div class="form-group">
            @Html.LabelFor(model => model.Prefijo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prefijo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prefijo,"" , new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion,"" , new { @class = "text-danger" })
            </div>
        </div>




WebGestion/WebGestion/Views/TiposFacturas/Index.cshtml
@model IEnumerable<WebGestion.Models.TiposFacturas>

@{
    ViewBag.Title = "Index";
}
<style type='text/css'>
    

</style>
<h2>Index</h2>
<h4>TiposFacturas</h4>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Prefijo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prefijo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>

    </tr>
}

</table>